language: php
git:
  quiet: true
  depth: 3
php:
- 7.2
addons:
  ssh_known_hosts:
  - $PRODUCTION_SERVER
branches:
  only:
  - prod
before_install:
- openssl aes-256-cbc -K $encrypted_32d47422b72a_key -iv $encrypted_32d47422b72a_iv
  -in id_rsa_mouWorks.enc -out /tmp/id_rsa_mouWorks -d
- chmod 600 /tmp/id_rsa_mouWorks
script:
- cd www
- composer install --no-dev --optimize-autoloader
- touch _conf/.env
- echo -e "CHATROOM_ID=$CHATROOM_ID" >> _conf/.env
- echo -e "LINE_BEARER=$LINE_BEARER" >> _conf/.env
- echo -e "TEST_SHIT=$TEST_SHIT" >> _conf/.env
- echo -e "SLACK_CHANNEL_WEBHOOKURL=$SLACK_CHANNEL_WEBHOOKURL" >> _conf/.env
- cd ..
- tar -czf code.tar.gz www
- scp -i /tmp/id_rsa_mouWorks -o StrictHostKeyChecking=no code.tar.gz update.sh ubuntu@$PRODUCTION_SERVER:/tmp
- ssh -i /tmp/id_rsa_mouWorks ubuntu@$PRODUCTION_SERVER " cd /tmp && sudo chmod +x update.sh
  && sudo ./update.sh "
cache:
  directories:
  - "$HOME/.composer/cache/files"
  - www/vendor
notifications:
  slack:
    rooms:
    - secure: kHvZIwGhXiKz0jAP546WcvDGAlmE4vHQFfjhb/5H+NUrR7NhT6VoWz77f3nj0icflpkXNCywxHVVlb4nPqYrSQU52CxE9a3p/DIbuCRcmO4Voe0IP3dJ7B1esVb6XbG6TLQVTEkoRLbyCNFOMtqPcdIw8F7O08n1UbcuUh6vv4wQqguqLjU6tcSz2hmnqIC4wLN4WpV8EFJB22pnCmF8DaLV3zB8BkgQkaWe01as85lyFCMfds5MO0OBsfN2z11X9TvpWUoEGvi7aA5cpwMWky8EFp9eFX+poj9COwev+fUxonuPL+pP8CQ8ujNm/AoZrECADjVGLB+Bn0/B33cK5GE84AGcfkJoabQGWzVbUHOLWM6Ht5LKPXNQVu7jUU7vtCnAyebuP1aqEOMrZ2aX0wi/bRwH4yqBadg7JcN38nSsFu8Ov8hIULPbLTfCSh8HjgEHPOq7TorfOIv+daY3X+cF6BaJcYlepc9hfTYOyRkQbybheh1XvTPpHBlDnJ6HI0gN/v7GDY/AtZKFNXl6l+1NCXX+ifdbcBHxlljjZNvV0MwmgekGF+3GeJ8F4XAiOINgcwvZOFH+sEg+7UZAWW2lfxAkYyOU7/cL3Z5sXW6Vmru3N5J7GCfkcOwzv6h6PQqojCKKJacBDb3zJOP/nfTHJwnLggHpE2In6/ggNcI=
    template:
    - " `%{result}` <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) in
      *%{duration}* "
    - " Repo: %{repository_slug} @ *%{branch}*"
    - " by *%{author}* "
env:
  matrix:
    secure: pgTV3JzUYeKqXAbDAg9qUnOifaOn73rv/kdGAesQNdInTgskZrVtmrBU+HB7FT/nEUX6QvFIE60Ste3nyuWygo/O7DlWEkU3cg2nJNZ0fUgfytuBYc2FInJK9hZhuVAvm8QvmuW7exDSVukAisQUPyP6T+yU5uAw3PpA7pJx9aBdxMDObYt5mMM34k03YwltJrPtf5opARKyg3TenC19PbUk2lOX/DH3kE7bO/4Y91xgQ9PFvJeydvDTbjFKUbZx56m88oxgPm7NJBVD0G6BeLkWQ1s10FCuLEwVWtAudSqudvQo5WAOYqAsrz+OuzJ6MLTVtFiFKCAuXZ72O8DS+xqNWGGkNW21RMthrdG2EycWow6xrFEE4Re3iZO3qNIM9gs0K4hhFm5BJNOVo0tJIxqb8t9mN6tI8DGWRbm+IvHLccWRvyElIDOsC+qruvF2fOnDaEgmjaB+A6CvrJJvCQYi9jSMTELpmgHwFOMtEQSTUZTbM1/mtavOBeTt9GDKDeoonQux5ufVd+ro5XE47BGEObefhXjJx8gdhhZdjxO6UP9habL5is6UL6fF+KV+7bMm9Rz+cV/iDQeOyKViB1hnCvl9ryaOll+LePhIgZc0q+lE0167Pyi+O5+LiGdp4NcJI/R9xYbzFN3YYLLYwM2vo1oZ9RzOrH84Ch7qPaU=
