#mou_nginx:
#  container_name: nginx
#  build: ./DockerConf/nginx
#  ports:
#  - "80:80"
#  volumes:
#  # source
#  - ./src/:/usr/share/nginx/html
#  links:
#  - mou_php_fpm

#mou_apache:
#  container_name: apache
#  build: ./DockerConf/apache
#  volumes:
#  - ./www::/var/www/html
#  links:
#  - mou_php_fpm
#  ports:
#  - "80:80"

mou_php_fpm:
  container_name: php_fpm
  build: ./DockerConf/php-fpm
  volumes:
  - ./www:/var/www/html
  links:
  - mou_mysql
  ports:
  - "80:80"

mou_mysql:
  container_name: mysql
  build: ./DockerConf/MySQL
  environment:
  - MYSQL_ROOT_PASSWORD=123456
  ports:
    - "3306:3306"

mou_adminer:
  container_name: adminer
  build: ./DockerConf/adminer
  ports:
    - "8080:8080"
  links:
    - mou_mysql