version: "3.2"
services:
  php:
    build: './DockerConf/php-fpm/'
    networks:
      - backend
    volumes:
      - ./www/:/var/www/html/
  apache:
    build: './DockerConf/apache/'
    depends_on:
      - php
      - mariadb
    networks:
      - frontend
      - backend
    ports: # Maps Local 8080 to 80 port @Docker Image
      - "8080:80"
    volumes:
      - ./www/:/var/www/html/
    links:
      - mariadb
  mariadb:
    build: './DockerConf/mariadb/'
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "3306:3306"
#    volumes:
#       - ./sql:/docker-entrypoint-initdb.d
networks:
  frontend:
  backend: