version: "3.2"
services:
  php:
    build: './DockerConf/php-fpm/'
    networks:
      - backend
    volumes:
      - ./www/:/var/www/html/
  apache:
    build: './DockerConf/apache/'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports: # Maps Local 8080 to 80 port @Docker Image
      - "8080:80"
    volumes:
      - ./www/:/var/www/html/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend: