version: "3.2"
services:
  php:
    build: './DockerConf/php-fpm/'
    networks:
      - backend
    volumes:
      - ./www/:/var/www/html/
  apache:
    build: './DockerConf/apache/'
    depends_on:
      - php
      - mariadb
    networks:
      - frontend
      - backend
    ports: # Maps Local 8080 to 80 port @Docker Image
      - "8080:80"
    volumes:
      - ./www/:/var/www/html/
  mariadb:
    image: mariadb:10.3
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
networks:
  frontend:
  backend: